-- ============================================================
-- Match Point Pride — sample data
-- scope: mpp
--
-- GENERATED by MatchPointPride/scripts/export-seed-sql.ts from the
-- app's own buildSeedData(). Do not hand-edit; regenerate.
--
-- Sample data, clearly marked. It exists so the owner can be shown a
-- working app before he has typed anything, and so the console has
-- something to display. Every member row carries is_demo = true, so
-- the whole lot can be removed with one delete on the day he
-- onboards for real.
-- ============================================================

-- Idempotent: re-running replaces the sample set rather than doubling it.
delete from payments    where tenant_id = 'mpp' and ref like 'SEED-%';
delete from attendance  where tenant_id = 'mpp' and kind = 'staff';
delete from enrollments where tenant_id = 'mpp' and member_id in
  (select id from members where tenant_id = 'mpp' and is_demo);
delete from members     where tenant_id = 'mpp' and is_demo;
delete from fee_rules   where tenant_id = 'mpp' and note = 'seed';
delete from batches     where tenant_id = 'mpp';
delete from coaches     where tenant_id = 'mpp';

do $$
declare
  v_centre bigint;
  v_batch  bigint;
  v_member bigint;
  v_enr    bigint;
begin
  select id into v_centre from centres where tenant_id = 'mpp' and code = 'narsingi';
  if v_centre is null then raise exception 'mpp centre missing — apply 0008 first'; end if;

  -- staff
  insert into coaches (tenant_id, name, role, phone, active)
  values ('mpp', 'Venu', 'Head Coach', null, true);
  insert into coaches (tenant_id, name, role, phone, active)
  values ('mpp', 'Srikanth B', 'Assistant Coach', null, true);
  insert into coaches (tenant_id, name, role, phone, active)
  values ('mpp', 'Pavani R', 'Junior Coach', null, true);
  insert into coaches (tenant_id, name, role, phone, active)
  values ('mpp', 'Ramu', 'Court Maintenance', null, true);
  insert into coaches (tenant_id, name, role, phone, active)
  values ('mpp', 'Kavitha', 'Front Desk', null, true);

  -- batches, each with the fee rule that resolve_fee() will find
  insert into batches (tenant_id, centre_id, code, name, sport, days, start_time, end_time, capacity, active, sort)
  values ('mpp', v_centre, 'kids-batch-a', 'Kids Batch A', 'badminton', array[1,2,3,4,5]::int[],
          '16:30', '17:30', 12, true, 1)
  returning id into v_batch;
  insert into fee_rules (tenant_id, label, centre_id, sport, batch_id, monthly_amount,
                         plan_amounts, admission_fee, effective_from, active, note)
  values ('mpp', 'Kids Batch A', v_centre, 'badminton', v_batch, 2000,
          '{}'::jsonb, 0, current_date - 400, true, 'seed');

  insert into batches (tenant_id, centre_id, code, name, sport, days, start_time, end_time, capacity, active, sort)
  values ('mpp', v_centre, 'kids-batch-b', 'Kids Batch B', 'badminton', array[1,2,3,4,5]::int[],
          '17:30', '18:30', 12, true, 2)
  returning id into v_batch;
  insert into fee_rules (tenant_id, label, centre_id, sport, batch_id, monthly_amount,
                         plan_amounts, admission_fee, effective_from, active, note)
  values ('mpp', 'Kids Batch B', v_centre, 'badminton', v_batch, 2000,
          '{}'::jsonb, 0, current_date - 400, true, 'seed');

  insert into batches (tenant_id, centre_id, code, name, sport, days, start_time, end_time, capacity, active, sort)
  values ('mpp', v_centre, 'kids-batch-c', 'Kids Batch C', 'badminton', array[1,2,3,4,5]::int[],
          '18:30', '19:30', 12, true, 3)
  returning id into v_batch;
  insert into fee_rules (tenant_id, label, centre_id, sport, batch_id, monthly_amount,
                         plan_amounts, admission_fee, effective_from, active, note)
  values ('mpp', 'Kids Batch C', v_centre, 'badminton', v_batch, 2200,
          '{}'::jsonb, 0, current_date - 400, true, 'seed');

  insert into batches (tenant_id, centre_id, code, name, sport, days, start_time, end_time, capacity, active, sort)
  values ('mpp', v_centre, 'kids-batch-d', 'Kids Batch D', 'badminton', array[1,2,3,4,5,6]::int[],
          '06:30', '07:30', 12, true, 4)
  returning id into v_batch;
  insert into fee_rules (tenant_id, label, centre_id, sport, batch_id, monthly_amount,
                         plan_amounts, admission_fee, effective_from, active, note)
  values ('mpp', 'Kids Batch D', v_centre, 'badminton', v_batch, 2200,
          '{}'::jsonb, 0, current_date - 400, true, 'seed');

  insert into batches (tenant_id, centre_id, code, name, sport, days, start_time, end_time, capacity, active, sort)
  values ('mpp', v_centre, 'professional-squad', 'Professional Squad', 'badminton', array[1,2,3,4,5,6]::int[],
          '05:30', '08:00', 10, true, 5)
  returning id into v_batch;
  insert into fee_rules (tenant_id, label, centre_id, sport, batch_id, monthly_amount,
                         plan_amounts, admission_fee, effective_from, active, note)
  values ('mpp', 'Professional Squad', v_centre, 'badminton', v_batch, 6000,
          '{}'::jsonb, 0, current_date - 400, true, 'seed');

  insert into batches (tenant_id, centre_id, code, name, sport, days, start_time, end_time, capacity, active, sort)
  values ('mpp', v_centre, 'membership', 'Membership', 'badminton', '{}'::int[],
          '05:00', '23:59', 40, true, 6)
  returning id into v_batch;
  insert into fee_rules (tenant_id, label, centre_id, sport, batch_id, monthly_amount,
                         plan_amounts, admission_fee, effective_from, active, note)
  values ('mpp', 'Membership', v_centre, 'badminton', v_batch, 1500,
          '{}'::jsonb, 0, current_date - 400, true, 'seed');

  -- students, as members + the enrolment that carries the money
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Aarav Reddy', 'Reddy family', '9433037974', 'badminton',
          '2026-04-01'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-a'),
          'badminton', 1, '2026-04-01'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Diya Sharma', 'Sharma family', '9418911684', 'badminton',
          '2026-02-02'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-b'),
          'badminton', 1, '2026-02-02'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Vihaan Rao', 'Rao family', '9441264286', 'badminton',
          '2026-03-30'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-c'),
          'badminton', 1, '2026-03-30'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Ananya Kumar', 'Kumar family', '9488361574', 'badminton',
          '2026-03-07'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-d'),
          'badminton', 1, '2026-03-07'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Arjun Nair', 'Nair family', '9444625559', 'badminton',
          '2026-02-20'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-a'),
          'badminton', 1, '2026-02-20'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Ishita Patel', 'Patel family', '9407549439', 'badminton',
          '2026-04-08'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-b'),
          'badminton', 1, '2026-04-08'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Rohan Verma', 'Verma family', '9490428591', 'badminton',
          '2026-03-04'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-c'),
          'badminton', 1, '2026-03-04'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Saanvi Iyer', 'Iyer family', '9452267789', 'badminton',
          '2026-03-19'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-d'),
          'badminton', 1, '2026-03-19'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Kabir Menon', 'Menon family', '9430862635', 'badminton',
          '2026-04-12'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-a'),
          'badminton', 1, '2026-04-12'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Myra Gupta', 'Gupta family', '9413941887', 'badminton',
          '2026-04-24'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-b'),
          'badminton', 1, '2026-04-24'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Advik Chowdary', 'Chowdary family', '9437545408', 'badminton',
          '2026-02-02'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-c'),
          'badminton', 1, '2026-02-02'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Anika Bose', 'Bose family', '9492278628', 'badminton',
          '2026-06-19'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-d'),
          'badminton', 1, '2026-06-19'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Reyansh Joshi', 'Joshi family', '9424859700', 'badminton',
          '2026-06-07'::date, 'discontinued', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-a'),
          'badminton', 1, '2026-06-07'::date,
          '2026-07-01'::date,
          'discontinued', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Kiara Pillai', 'Pillai family', '9401619355', 'badminton',
          '2026-02-25'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-b'),
          'badminton', 1, '2026-02-25'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Neel Shetty', 'Shetty family', '9497205069', 'badminton',
          '2026-02-04'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-c'),
          'badminton', 1, '2026-02-04'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Aadhya Raju', 'Raju family', '9463298816', 'badminton',
          '2026-02-15'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-d'),
          'badminton', 1, '2026-02-15'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Vivaan Desai', 'Desai family', '9486949315', 'badminton',
          '2026-05-10'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-a'),
          'badminton', 1, '2026-05-10'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Tara Krishnan', 'Krishnan family', '9403675842', 'badminton',
          '2026-04-06'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-b'),
          'badminton', 1, '2026-04-06'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Shaurya Malhotra', 'Malhotra family', '9456993288', 'badminton',
          '2026-03-02'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-c'),
          'badminton', 1, '2026-03-02'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Riya Naidu', 'Naidu family', '9489708248', 'badminton',
          '2026-04-20'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-d'),
          'badminton', 1, '2026-04-20'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Dhruv Prasad', 'Prasad family', '9410710274', 'badminton',
          '2026-04-27'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-a'),
          'badminton', 1, '2026-04-27'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Meera Salian', 'Salian family', '9442245344', 'badminton',
          '2026-04-06'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-b'),
          'badminton', 1, '2026-04-06'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Yuvan Hegde', 'Hegde family', '9438837587', 'badminton',
          '2026-03-31'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-c'),
          'badminton', 1, '2026-03-31'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Nitara Varma', 'Varma family', '9452855893', 'badminton',
          '2026-02-26'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-d'),
          'badminton', 1, '2026-02-26'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Aryan Goud', 'Goud family', '9443933172', 'badminton',
          '2026-02-14'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-a'),
          'badminton', 1, '2026-02-14'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Pari Sinha', 'Sinha family', '9424247697', 'badminton',
          '2026-05-30'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-b'),
          'badminton', 1, '2026-05-30'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Krish Bhatia', 'Bhatia family', '9474513893', 'badminton',
          '2026-03-24'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-c'),
          'badminton', 1, '2026-03-24'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Zara Qureshi', 'Qureshi family', '9438416966', 'badminton',
          '2026-05-25'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-d'),
          'badminton', 1, '2026-05-25'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Ved Kulkarni', 'Kulkarni family', '9479214899', 'badminton',
          '2026-06-26'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-a'),
          'badminton', 1, '2026-06-26'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Amaira Jain', 'Jain family', '9461841461', 'badminton',
          '2026-02-21'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='kids-batch-b'),
          'badminton', 1, '2026-02-21'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Sai Charan', null, '9412500788', 'badminton',
          '2026-01-27'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='professional-squad'),
          'badminton', 1, '2026-01-27'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Harini Rao', null, '9404550890', 'badminton',
          '2026-02-03'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='professional-squad'),
          'badminton', 1, '2026-02-03'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Nikhil Teja', null, '9493869523', 'badminton',
          '2026-02-05'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='professional-squad'),
          'badminton', 1, '2026-02-05'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Sneha Reddy', null, '9491021334', 'badminton',
          '2026-06-15'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='professional-squad'),
          'badminton', 1, '2026-06-15'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Karthik M', null, '9498368905', 'badminton',
          '2026-05-22'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='professional-squad'),
          'badminton', 1, '2026-05-22'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Pooja Ravi', null, '9456797534', 'badminton',
          '2026-04-30'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='professional-squad'),
          'badminton', 1, '2026-04-30'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Abhinav S', null, '9443843084', 'badminton',
          '2026-05-11'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='professional-squad'),
          'badminton', 1, '2026-05-11'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Ramesh Babu', null, '9486797592', 'badminton',
          '2026-02-15'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-02-15'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Lakshmi Devi', null, '9495892998', 'badminton',
          '2026-06-04'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-06-04'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Suresh Kumar', null, '9440649240', 'badminton',
          '2026-07-03'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-07-03'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Fatima Begum', null, '9441319795', 'badminton',
          '2026-04-04'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-04-04'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Prakash Rao', null, '9498395063', 'badminton',
          '2026-03-17'::date, 'discontinued', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-03-17'::date,
          '2026-07-01'::date,
          'discontinued', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Anil Varma', null, '9441074154', 'badminton',
          '2026-02-24'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-02-24'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Deepa Menon', null, '9487736116', 'badminton',
          '2026-02-20'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-02-20'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Vinod Chandra', null, '9470707154', 'badminton',
          '2026-04-15'::date, 'discontinued', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-04-15'::date,
          '2026-07-15'::date,
          'discontinued', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Sunita Agarwal', null, '9452909139', 'badminton',
          '2026-06-20'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-06-20'::date,
          '2026-07-01'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Mahesh Yadav', null, '9446259665', 'badminton',
          '2026-02-05'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-02-05'::date,
          '2026-07-05'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Rajiv Khanna', null, '9476562130', 'badminton',
          '2026-06-26'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-06-26'::date,
          '2026-07-10'::date,
          'active', null)
  returning id into v_enr;
  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)
  values ('mpp', 'Geetha Rani', null, '9422687452', 'badminton',
          '2026-04-05'::date, 'active', 'narsingi', true, null)
  returning id into v_member;
  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,
                           joined_on, renewal_on, status, discontinued_on)
  values ('mpp', v_member, v_centre, (select id from batches where tenant_id='mpp' and code='membership'),
          'badminton', 1, '2026-04-05'::date,
          '2026-07-15'::date,
          'active', null)
  returning id into v_enr;

  -- revenue not tied to an enrolment (court hire, memberships, sundry)
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-07-29'::date, 'SEED-R0', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-07-28'::date, 'SEED-R1', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-07-27'::date, 'SEED-R2', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-07-25'::date, 'SEED-R3', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-07-24'::date, 'SEED-R4', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-07-23'::date, 'SEED-R5', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-07-22'::date, 'SEED-R6', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-07-21'::date, 'SEED-R7', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-07-19'::date, 'SEED-R8', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-07-17'::date, 'SEED-R9', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-07-16'::date, 'SEED-R10', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-07-15'::date, 'SEED-R11', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-07-14'::date, 'SEED-R12', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-07-13'::date, 'SEED-R13', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-07-12'::date, 'SEED-R14', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-07-11'::date, 'SEED-R15', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-07-09'::date, 'SEED-R16', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-07-08'::date, 'SEED-R17', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-07-07'::date, 'SEED-R18', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-07-06'::date, 'SEED-R19', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-07-05'::date, 'SEED-R20', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-07-04'::date, 'SEED-R21', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-07-02'::date, 'SEED-R22', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-07-01'::date, 'SEED-R23', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-06-30'::date, 'SEED-R24', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-06-29'::date, 'SEED-R25', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-06-26'::date, 'SEED-R26', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-06-25'::date, 'SEED-R27', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-06-23'::date, 'SEED-R28', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-06-22'::date, 'SEED-R29', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-06-21'::date, 'SEED-R30', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-06-19'::date, 'SEED-R31', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-06-18'::date, 'SEED-R32', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-06-15'::date, 'SEED-R33', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-06-14'::date, 'SEED-R34', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-06-13'::date, 'SEED-R35', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-06-12'::date, 'SEED-R36', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-06-11'::date, 'SEED-R37', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-06-10'::date, 'SEED-R38', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-06-09'::date, 'SEED-R39', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-06-08'::date, 'SEED-R40', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-06-06'::date, 'SEED-R41', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-06-05'::date, 'SEED-R42', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-06-04'::date, 'SEED-R43', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-06-03'::date, 'SEED-R44', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-05-31'::date, 'SEED-R45', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-05-30'::date, 'SEED-R46', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-05-29'::date, 'SEED-R47', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-05-27'::date, 'SEED-R48', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-05-26'::date, 'SEED-R49', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-05-25'::date, 'SEED-R50', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-05-23'::date, 'SEED-R51', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-05-22'::date, 'SEED-R52', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-05-21'::date, 'SEED-R53', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-05-20'::date, 'SEED-R54', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-05-19'::date, 'SEED-R55', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-05-18'::date, 'SEED-R56', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-05-17'::date, 'SEED-R57', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-05-16'::date, 'SEED-R58', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-05-15'::date, 'SEED-R59', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-05-14'::date, 'SEED-R60', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-05-13'::date, 'SEED-R61', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-05-12'::date, 'SEED-R62', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-05-11'::date, 'SEED-R63', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-05-10'::date, 'SEED-R64', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-05-09'::date, 'SEED-R65', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-05-08'::date, 'SEED-R66', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-05-06'::date, 'SEED-R67', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-05-05'::date, 'SEED-R68', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-05-04'::date, 'SEED-R69', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-05-02'::date, 'SEED-R70', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-05-01'::date, 'SEED-R71', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-04-30'::date, 'SEED-R72', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-04-27'::date, 'SEED-R73', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-04-26'::date, 'SEED-R74', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-04-25'::date, 'SEED-R75', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-04-24'::date, 'SEED-R76', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-04-23'::date, 'SEED-R77', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-04-21'::date, 'SEED-R78', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-04-20'::date, 'SEED-R79', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-04-19'::date, 'SEED-R80', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-04-18'::date, 'SEED-R81', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-04-15'::date, 'SEED-R82', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-04-14'::date, 'SEED-R83', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-04-13'::date, 'SEED-R84', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-04-12'::date, 'SEED-R85', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-04-11'::date, 'SEED-R86', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-04-10'::date, 'SEED-R87', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-04-09'::date, 'SEED-R88', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-04-08'::date, 'SEED-R89', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-04-07'::date, 'SEED-R90', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-04-06'::date, 'SEED-R91', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-04-05'::date, 'SEED-R92', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-04-04'::date, 'SEED-R93', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-04-03'::date, 'SEED-R94', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-04-02'::date, 'SEED-R95', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-04-01'::date, 'SEED-R96', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-03-31'::date, 'SEED-R97', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-03-30'::date, 'SEED-R98', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-03-29'::date, 'SEED-R99', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-03-28'::date, 'SEED-R100', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-03-27'::date, 'SEED-R101', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-03-26'::date, 'SEED-R102', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-03-24'::date, 'SEED-R103', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-03-23'::date, 'SEED-R104', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-03-21'::date, 'SEED-R105', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-03-19'::date, 'SEED-R106', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-03-18'::date, 'SEED-R107', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-03-16'::date, 'SEED-R108', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-03-14'::date, 'SEED-R109', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-03-13'::date, 'SEED-R110', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-03-12'::date, 'SEED-R111', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-03-11'::date, 'SEED-R112', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-03-10'::date, 'SEED-R113', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-03-09'::date, 'SEED-R114', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-03-07'::date, 'SEED-R115', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-03-06'::date, 'SEED-R116', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-03-05'::date, 'SEED-R117', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-03-04'::date, 'SEED-R118', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-03-03'::date, 'SEED-R119', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-03-02'::date, 'SEED-R120', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-02-28'::date, 'SEED-R121', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-02-27'::date, 'SEED-R122', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-02-26'::date, 'SEED-R123', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-02-24'::date, 'SEED-R124', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-02-23'::date, 'SEED-R125', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-02-22'::date, 'SEED-R126', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-02-21'::date, 'SEED-R127', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-02-20'::date, 'SEED-R128', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-02-19'::date, 'SEED-R129', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-02-18'::date, 'SEED-R130', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-02-17'::date, 'SEED-R131', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-02-16'::date, 'SEED-R132', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3500,
          'UPI', '2026-02-14'::date, 'SEED-R133', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-02-13'::date, 'SEED-R134', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 3000,
          'UPI', '2026-02-12'::date, 'SEED-R135', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4000,
          'UPI', '2026-02-10'::date, 'SEED-R136', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-02-09'::date, 'SEED-R137', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-02-07'::date, 'SEED-R138', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2000,
          'UPI', '2026-02-06'::date, 'SEED-R139', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 2500,
          'UPI', '2026-02-05'::date, 'SEED-R140', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 5000,
          'UPI', '2026-02-04'::date, 'SEED-R141', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 1500,
          'UPI', '2026-02-03'::date, 'SEED-R142', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-02-02'::date, 'SEED-R143', 'paid', null);
  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)
  values ('mpp', 'Court Booking', 'Court', 'Hourly court bookings', 4500,
          'UPI', '2026-02-01'::date, 'SEED-R144', 'paid', null);

  -- expenses
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E0', 'Marketing', null, null,
          4178, 'UPI', '2026-07-17'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E1', 'Salaries', null, 'Monthly staff salaries',
          69000, 'UPI', '2026-07-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E2', 'Court Maintenance', null, null,
          4740, 'UPI', '2026-07-02'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E3', 'Electricity & Water', null, null,
          9415, 'UPI', '2026-07-02'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E4', 'Rent', null, null,
          38000, 'UPI', '2026-07-02'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E5', 'Shuttles & Equipment', null, null,
          17334, 'UPI', '2026-07-01'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E6', 'Salaries', null, 'Monthly staff salaries',
          69000, 'UPI', '2026-06-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E7', 'Electricity & Water', null, null,
          11515, 'UPI', '2026-06-04'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E8', 'Rent', null, null,
          38000, 'UPI', '2026-06-04'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E9', 'Shuttles & Equipment', null, null,
          16587, 'UPI', '2026-06-03'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E10', 'Court Maintenance', null, null,
          7137, 'UPI', '2026-06-02'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E11', 'Salaries', null, 'Monthly staff salaries',
          69000, 'UPI', '2026-05-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E12', 'Shuttles & Equipment', null, null,
          14929, 'UPI', '2026-05-03'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E13', 'Electricity & Water', null, null,
          11130, 'UPI', '2026-05-03'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E14', 'Court Maintenance', null, null,
          4300, 'UPI', '2026-05-01'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E15', 'Rent', null, null,
          38000, 'UPI', '2026-05-01'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E16', 'Marketing', null, null,
          8406, 'UPI', '2026-04-17'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E17', 'Salaries', null, 'Monthly staff salaries',
          69000, 'UPI', '2026-04-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E18', 'Rent', null, null,
          38000, 'UPI', '2026-04-04'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E19', 'Shuttles & Equipment', null, null,
          15820, 'UPI', '2026-04-03'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E20', 'Court Maintenance', null, null,
          5893, 'UPI', '2026-04-02'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E21', 'Electricity & Water', null, null,
          11912, 'UPI', '2026-04-01'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E22', 'Salaries', null, 'Monthly staff salaries',
          69000, 'UPI', '2026-03-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E23', 'Shuttles & Equipment', null, null,
          20349, 'UPI', '2026-03-04'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E24', 'Electricity & Water', null, null,
          9490, 'UPI', '2026-03-04'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E25', 'Court Maintenance', null, null,
          6188, 'UPI', '2026-03-02'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E26', 'Rent', null, null,
          38000, 'UPI', '2026-03-01'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E27', 'Salaries', null, 'Monthly staff salaries',
          69000, 'UPI', '2026-02-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E28', 'Shuttles & Equipment', null, null,
          15710, 'UPI', '2026-02-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E29', 'Electricity & Water', null, null,
          10275, 'UPI', '2026-02-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E30', 'Rent', null, null,
          38000, 'UPI', '2026-02-05'::date);
  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)
  values ('mpp', 'SEED-E31', 'Court Maintenance', null, null,
          5313, 'UPI', '2026-02-04'::date);

  -- staff attendance, last 30 days
  insert into attendance (tenant_id, date, kind, person_id, present)
  select 'mpp', d::date, 'staff', c.id::text, true
    from generate_series(current_date - 29, current_date, interval '1 day') d
    cross join (select id from coaches where tenant_id = 'mpp') c
   where extract(isodow from d) <> 7
  on conflict do nothing;

end $$;

-- Per-batch UPI ids. These live in tenants.config rather than a new
-- column on the shared batches table, per the platform rule that
-- per-tenant behaviour goes in config jsonb.
update tenants
   set config = jsonb_set(coalesce(config, '{}'::jsonb), '{billing,upiByBatch}',
         '{"kids-batch-a":{"upi":"7732077327@ybl","payee":"Match Point Badminton Academy"},"kids-batch-b":{"upi":"7732077327@ybl","payee":"Match Point Badminton Academy"},"kids-batch-c":{"upi":"7732077327@ybl","payee":"Match Point Badminton Academy"},"kids-batch-d":{"upi":"7732077327@ybl","payee":"Match Point Badminton Academy"},"professional-squad":{"upi":"7732077327@ybl","payee":"Match Point Badminton Academy"},"membership":{"upi":"7732077327@ybl","payee":"Match Point Badminton Academy"}}'::jsonb, true)
 where id = 'mpp';

-- Prove the shape, and that the money chain resolves for a real batch.
do $$
declare v_b int; v_m int; v_e int; v_c int; v_fee jsonb; v_batch bigint;
begin
  select count(*) into v_b from batches where tenant_id='mpp';
  select count(*) into v_m from members where tenant_id='mpp' and is_demo;
  select count(*) into v_e from enrollments where tenant_id='mpp';
  select count(*) into v_c from coaches where tenant_id='mpp';
  if v_b <> 6 then raise exception 'batches: expected 6, got %', v_b; end if;
  if v_m <> 49 then raise exception 'members: expected 49, got %', v_m; end if;
  if v_e <> 49 then raise exception 'enrollments: expected 49, got %', v_e; end if;
  if v_c <> 5 then raise exception 'coaches: expected 5, got %', v_c; end if;

  select id into v_batch from batches where tenant_id='mpp' and code='kids-batch-a';
  v_fee := resolve_fee('mpp', null, (select id from centres where tenant_id='mpp' and code='narsingi'),
                       'badminton', v_batch, 1, null);
  if (v_fee->>'source') <> 'batch' then
    raise exception 'fee for Kids Batch A resolved from %, not the batch rule', v_fee->>'source';
  end if;
  if (v_fee->>'amount')::numeric <> 2000 then
    raise exception 'Kids Batch A fee is %, expected 2000', v_fee->>'amount';
  end if;

  raise notice 'mpp seeded: % batches, % members, % coaches', v_b, v_m, v_c;
end $$;
